<div class="container">    
    <h2><?php $this->getPageTitle() ?></h2>
    <p class="mb-3">Olá, <?php echo $this->view->nome ?>!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Veritatis, ipsa, iusto molestiae omnis odio labore adipisci repellendus nam error iste distinctio eum placeat ullam nostrum id! Consectetur, culpa nemo officiis!</p>
    <p>Minima, est, autem, aut natus corrupti praesentium iste ipsum recusandae saepe illum nobis doloribus officia incidunt earum quod hic nesciunt atque possimus id asperiores voluptatibus quisquam vitae quis architecto rerum.</p>
    <p>Magni, deserunt, laborum, suscipit, cumque delectus officia non mollitia laudantium illo ab officiis vel! Iure, iste, delectus deserunt quod culpa in omnis magni quaerat aut voluptas illum voluptates fugiat accusamus?</p>
    <p>Blanditiis neque aperiam obcaecati aut pariatur in suscipit modi unde est ducimus! Necessitatibus, velit, dolorum tempora ab eos ullam eligendi minus doloribus soluta. Voluptatibus rem adipisci culpa harum distinctio accusamus?</p>
    <p>Numquam, omnis, blanditiis, nihil cum animi tenetur voluptatum laborum porro eligendi voluptate sapiente facilis! Assumenda, voluptatem, ullam, quis, ratione sit voluptates eligendi saepe ut a architecto alias neque beatae reiciendis.</p>
</div>