<div class="container">
    <h2 class="mb-4">Criar post</h2>
    <div class="row">
        <div class="col-lg-8">
            <form action="/post/store" method="post" accept-charset="utf-8">
                <div class="form-group">
                    <label for="title">Título</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="Título do post">
                </div>
                <div class="form-group">
                    <label for="content">Conteúdo</label>
                    <textarea name="content"  id="content" cols="30" rows="10" class="form-control" placeholder="Conteúdo"></textarea>
                </div>
                <input type="submit" class="btn btn-success" value="Enviar">
                <a href="/posts" class="btn btn-danger">Cancelar</a>
            </form>
        </div>
    </div>
</div>